# crewai_deploy.yml workflow je dočasne deaktivovaný, aby nespôsoboval chyby v Actions.
# Ak chcete workflow aktivovať, doplňte sem reálnu definíciu.

name: crewai_deploy (DISABLED)

on:
  workflow_dispatch:

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - name: CrewAI deploy workflow is currently disabled
        run: echo "This workflow is intentionally disabled."
